production:
  sessions:
    default:
      database: votalo
      hosts:
        - localhost:27017
      options:
        consistency: :strong
development:
  sessions:
    default:
      database: votalo_development
      hosts:
        - localhost:27017
      options:
        consistency: :strong
test:
  sessions:
    default:
      database: votalo_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
